title: Dunish
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
navigation:
  - title: Home
    url: docs/index.md
  - title: The 10 rules
    url: docs/100_baze_regule.md

