site_name: Dunish
site_url: http://www.pandunia.info/dunish/finish
repo_url: https://github.com/barumau/dunish/
site_author: Risto Kupsala
docs_dir: ../../finish
site_dir: ../../html/finish
theme: readthedocs
nav:
    - Kotisivu: 'index.md'
    - 'Kielioppi':
        - '10 sääntöä': 100_baze_regule.md
        - 'Kansainväliset sanat': 101_dunia_worde.md
        - 'Kirjoitus ja ääntäminen': 102_ortografie.md
        - 'Sanojen painotus': 103_aksente.md
        - Substantiivit : 104_nome.md
        - Lukusanat: 105_numer.md
        - Pronominit: 107_pronome.md
        - Verbit: 108_verbe.md
        - 'Sanojen johtaminen': 110_worde_kostrution.md
    - Oppitunteja:
        - '1. oppitunti': 201_lecion_1.md
    - 'Taustatietoja':
        - 'Idea': 301_idea_of_Dunish.md
        - 'Dunish vs. englanti': 302_Dunish_vs_English.md
